[2025-07-28T23:27:02.541+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-28T23:27:02.560+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training manual__2025-07-28T23:21:04.451933+00:00 [queued]>
[2025-07-28T23:27:02.568+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training manual__2025-07-28T23:21:04.451933+00:00 [queued]>
[2025-07-28T23:27:02.568+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-07-28T23:27:02.579+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_training> on 2025-07-28 23:21:04.451933+00:00
[2025-07-28T23:27:02.585+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=122) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-28T23:27:02.590+0000] {standard_task_runner.py:72} INFO - Started process 123 to run task
[2025-07-28T23:27:02.589+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'execute_training', 'manual__2025-07-28T23:21:04.451933+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmpka3y8t37']
[2025-07-28T23:27:02.591+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask execute_training
[2025-07-28T23:27:02.634+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.execute_training manual__2025-07-28T23:21:04.451933+00:00 [running]> on host b2497d67dac2
[2025-07-28T23:27:02.713+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kanewyp' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='execute_training' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T23:21:04.451933+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T23:21:04.451933+00:00'
[2025-07-28T23:27:02.714+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-28T23:27:07.907+0000] {font_manager.py:1639} INFO - generated new fontManager
[2025-07-28T23:27:08.121+0000] {fraud_detection_training_dag.py:23} INFO - Initializing Fraud Detection Training
[2025-07-28T23:27:08.130+0000] {fraud_detection_training.py:62} INFO - Configuration loaded successfully
[2025-07-28T23:27:08.685+0000] {fraud_detection_training.py:88} INFO - Connected to MinIO. Available buckets: mlflow
[2025-07-28T23:27:09.299+0000] {fraud_detection_training.py:182} INFO - Starting model training process...
[2025-07-28T23:27:09.300+0000] {fraud_detection_training.py:104} INFO - Reading data from Kafka topic: fraud_detection
[2025-07-28T23:27:09.973+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('13.237.143.76', 9092)]>: connecting to pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 [('13.237.143.76', 9092) IPv4]
[2025-07-28T23:27:10.013+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('13.237.143.76', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-07-28T23:27:10.150+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <checking_api_versions_recv> [IPv4 ('13.237.143.76', 9092)]>: Broker version identified as 2.6
[2025-07-28T23:27:10.317+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('13.237.143.76', 9092)]>: Authenticated as KQIWVOLDBVJZDLTP via SASL / Plain
[2025-07-28T23:27:10.318+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.237.143.76', 9092)]>: Connection complete.
[2025-07-28T23:27:10.319+0000] {consumer.py:120} WARNING - group_id is None: disabling auto-commit.
[2025-07-28T23:27:10.319+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('fraud_detection',)
[2025-07-28T23:27:10.359+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('fraud_detection', 0), ('fraud_detection', 1), ('fraud_detection', 2), ('fraud_detection', 3), ('fraud_detection', 4), ('fraud_detection', 5)]
[2025-07-28T23:27:10.439+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('13.237.213.69', 9092)]>: connecting to b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 [('13.237.213.69', 9092) IPv4]
[2025-07-28T23:27:10.502+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=b1-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('52.63.214.73', 9092)]>: connecting to b1-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 [('52.63.214.73', 9092) IPv4]
[2025-07-28T23:27:10.572+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=2 host=b2-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('13.210.234.188', 9092)]>: connecting to b2-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 [('13.210.234.188', 9092) IPv4]
[2025-07-28T23:27:10.634+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=3 host=b3-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('52.63.252.19', 9092)]>: connecting to b3-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 [('52.63.252.19', 9092) IPv4]
[2025-07-28T23:27:10.705+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=4 host=b4-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('13.210.104.107', 9092)]>: connecting to b4-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 [('13.210.104.107', 9092) IPv4]
[2025-07-28T23:27:10.774+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=5 host=b5-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connecting> [IPv4 ('13.237.226.149', 9092)]>: connecting to b5-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 [('13.237.226.149', 9092) IPv4]
[2025-07-28T23:27:10.776+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('13.237.213.69', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-07-28T23:27:10.795+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=b1-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('52.63.214.73', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-07-28T23:27:10.811+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=2 host=b2-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('13.210.234.188', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-07-28T23:27:10.826+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=3 host=b3-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('52.63.252.19', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-07-28T23:27:10.846+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=4 host=b4-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('13.210.104.107', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-07-28T23:27:10.886+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=5 host=b5-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <handshake> [IPv4 ('13.237.226.149', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-07-28T23:27:11.092+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('13.237.213.69', 9092)]>: Authenticated as KQIWVOLDBVJZDLTP via SASL / Plain
[2025-07-28T23:27:11.093+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.237.213.69', 9092)]>: Connection complete.
[2025-07-28T23:27:11.093+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.237.143.76', 9092)]>: Closing connection. 
[2025-07-28T23:27:11.217+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=2 host=b2-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('13.210.234.188', 9092)]>: Authenticated as KQIWVOLDBVJZDLTP via SASL / Plain
[2025-07-28T23:27:11.218+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=2 host=b2-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.210.234.188', 9092)]>: Connection complete.
[2025-07-28T23:27:11.257+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=b1-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('52.63.214.73', 9092)]>: Authenticated as KQIWVOLDBVJZDLTP via SASL / Plain
[2025-07-28T23:27:11.258+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=b1-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('52.63.214.73', 9092)]>: Connection complete.
[2025-07-28T23:27:11.431+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=4 host=b4-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('13.210.104.107', 9092)]>: Authenticated as KQIWVOLDBVJZDLTP via SASL / Plain
[2025-07-28T23:27:11.432+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=4 host=b4-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.210.104.107', 9092)]>: Connection complete.
[2025-07-28T23:27:11.566+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=3 host=b3-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('52.63.252.19', 9092)]>: Authenticated as KQIWVOLDBVJZDLTP via SASL / Plain
[2025-07-28T23:27:11.567+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=3 host=b3-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('52.63.252.19', 9092)]>: Connection complete.
[2025-07-28T23:27:11.568+0000] {fetcher.py:418} INFO - Resetting offset for partition ('fraud_detection', 2) to offset 0.
[2025-07-28T23:27:11.694+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=5 host=b5-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <authenticating> [IPv4 ('13.237.226.149', 9092)]>: Authenticated as KQIWVOLDBVJZDLTP via SASL / Plain
[2025-07-28T23:27:11.696+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=5 host=b5-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.237.226.149', 9092)]>: Connection complete.
[2025-07-28T23:27:11.697+0000] {fetcher.py:418} INFO - Resetting offset for partition ('fraud_detection', 1) to offset 0.
[2025-07-28T23:27:11.698+0000] {fetcher.py:418} INFO - Resetting offset for partition ('fraud_detection', 0) to offset 0.
[2025-07-28T23:27:11.700+0000] {fetcher.py:418} INFO - Resetting offset for partition ('fraud_detection', 4) to offset 0.
[2025-07-28T23:27:11.736+0000] {fetcher.py:418} INFO - Resetting offset for partition ('fraud_detection', 5) to offset 0.
[2025-07-28T23:27:11.740+0000] {fetcher.py:418} INFO - Resetting offset for partition ('fraud_detection', 3) to offset 0.
[2025-07-28T23:27:52.614+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.237.213.69', 9092)]>: Closing connection. 
[2025-07-28T23:27:52.615+0000] {fetcher.py:786} INFO - Fetch to node 0 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=0 host=b0-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.237.213.69', 9092)]>
[2025-07-28T23:27:52.616+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=b1-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('52.63.214.73', 9092)]>: Closing connection. 
[2025-07-28T23:27:52.617+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=b1-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('52.63.214.73', 9092)]>
[2025-07-28T23:27:52.617+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=2 host=b2-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.210.234.188', 9092)]>: Closing connection. 
[2025-07-28T23:27:52.618+0000] {fetcher.py:786} INFO - Fetch to node 2 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=2 host=b2-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.210.234.188', 9092)]>
[2025-07-28T23:27:52.618+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=3 host=b3-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('52.63.252.19', 9092)]>: Closing connection. 
[2025-07-28T23:27:52.619+0000] {fetcher.py:786} INFO - Fetch to node 3 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=3 host=b3-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('52.63.252.19', 9092)]>
[2025-07-28T23:27:52.619+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=4 host=b4-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.210.104.107', 9092)]>: Closing connection. 
[2025-07-28T23:27:52.620+0000] {fetcher.py:786} INFO - Fetch to node 4 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=4 host=b4-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.210.104.107', 9092)]>
[2025-07-28T23:27:52.620+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=5 host=b5-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.237.226.149', 9092)]>: Closing connection. 
[2025-07-28T23:27:52.621+0000] {fetcher.py:786} INFO - Fetch to node 5 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=5 host=b5-pkc-ldvj1.ap-southeast-2.aws.confluent.cloud:9092 <connected> [IPv4 ('13.237.226.149', 9092)]>
[2025-07-28T23:27:54.225+0000] {fraud_detection_training.py:131} INFO - Received 371760 records from Kafka with fraud rate: 0.74%
[2025-07-28T23:28:06.089+0000] {fraud_detection_training.py:261} INFO - Starting hyperparameter tuning...
[2025-07-28T23:28:06.093+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-07-28T23:28:38.729+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-07-28T23:28:38.730+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-28T23:28:38.731+0000] {process_utils.py:132} INFO - Sending 15 to group 123. PIDs of all processes in the group: [123]
[2025-07-28T23:28:38.732+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 123
[2025-07-28T23:28:39.063+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-28T23:28:39.108+0000] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
  File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 62, in main
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 64, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 237, in worker
    _run_command_with_daemon_option(
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 50, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 230, in run_celery_worker
    celery_app.worker_main(options)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
  File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
  File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
  File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 651, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 139, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
  File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 171, in _execute_in_fork
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/***/dags/fraud_detection_training_dag.py", line 25, in _train_model
    model, precision = trainer.train_model()
  File "/opt/***/dags/fraud_detection_training.py", line 262, in train_model
    searcher.fit(X_train, y_train)
  File "/home/***/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/sklearn/model_selection/_search.py", line 1024, in fit
    self._run_search(evaluate_candidates)
  File "/home/***/.local/lib/python3.12/site-packages/sklearn/model_selection/_search.py", line 1951, in _run_search
    evaluate_candidates(
  File "/home/***/.local/lib/python3.12/site-packages/sklearn/model_selection/_search.py", line 970, in evaluate_candidates
    out = parallel(
  File "/home/***/.local/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/***/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/***/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/***/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/imblearn/pipeline.py", line 526, in fit
    self._final_estimator.fit(Xt, yt, **last_step_params["fit"])
  File "/home/***/.local/lib/python3.12/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/xgboost/sklearn.py", line 1682, in fit
    self._Booster = train(
  File "/home/***/.local/lib/python3.12/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/xgboost/training.py", line 183, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/***/.local/lib/python3.12/site-packages/xgboost/core.py", line 2247, in update
    _LIB.XGBoosterUpdateOneIter(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-07-28T23:28:39.135+0000] {logging_mixin.py:190} INFO - 🏃 View run classy-lynx-639 at: http://mlflow-server:5500/#/experiments/1/runs/b0ec5819049a44fca3373d046ed954c5
[2025-07-28T23:28:39.136+0000] {logging_mixin.py:190} INFO - 🧪 View experiment at: http://mlflow-server:5500/#/experiments/1
[2025-07-28T23:28:39.172+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 25, in _train_model
    model, precision = trainer.train_model()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fraud_detection_training.py", line 262, in train_model
    searcher.fit(X_train, y_train)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_search.py", line 1024, in fit
    self._run_search(evaluate_candidates)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_search.py", line 1951, in _run_search
    evaluate_candidates(
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_search.py", line 970, in evaluate_candidates
    out = parallel(
          ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/imblearn/pipeline.py", line 526, in fit
    self._final_estimator.fit(Xt, yt, **last_step_params["fit"])
  File "/home/airflow/.local/lib/python3.12/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/xgboost/sklearn.py", line 1682, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/xgboost/training.py", line 183, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/airflow/.local/lib/python3.12/site-packages/xgboost/core.py", line 2247, in update
    _LIB.XGBoosterUpdateOneIter(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-07-28T23:28:39.177+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=fraud_detection_training, task_id=execute_training, run_id=manual__2025-07-28T23:21:04.451933+00:00, execution_date=20250728T232104, start_date=20250728T232702, end_date=20250728T232839
[2025-07-28T23:28:39.212+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-28T23:28:39.313+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=123, status='terminated', exitcode=2, started='23:27:01') (123) terminated with exit code 2
